default_events:
  - release
  - check_run

default_permissions:
  contents: write
  metadata: read
  pull_requests: write
  checks: read

name: Lvce Editor Helper Bot
url: https://github.com/lvce-editor/helper-bot
description: GitHub App to automatically update lvce editor extensions to latest versions.
public: false
