export const ERROR_CODES = {
  ADD_GITATTRIBUTES_FAILED: 'ADD_GITATTRIBUTES_FAILED',
  ADD_OIDC_PERMISSIONS_FAILED: 'ADD_OIDC_PERMISSIONS_FAILED',
  COMPUTE_DOCKERFILE_CONTENT_FAILED: 'COMPUTE_DOCKERFILE_CONTENT_FAILED',
  COMPUTE_ENSURE_LERNA_EXCLUDED_FAILED: 'COMPUTE_ENSURE_LERNA_EXCLUDED_FAILED',
  COMPUTE_GITPOD_DOCKERFILE_CONTENT_FAILED:
    'COMPUTE_GITPOD_DOCKERFILE_CONTENT_FAILED',
  COMPUTE_NVMRC_CONTENT_FAILED: 'COMPUTE_NVMRC_CONTENT_FAILED',
  GET_NEW_PACKAGE_FILES_FAILED: 'GET_NEW_PACKAGE_FILES_FAILED',
  REMOVE_NPM_TOKEN_FAILED: 'REMOVE_NPM_TOKEN_FAILED',
  UPDATE_DEPENDENCIES_FAILED: 'UPDATE_DEPENDENCIES_FAILED',
  UPDATE_NODE_VERSION_FAILED: 'UPDATE_NODE_VERSION_FAILED',
  WRAP_COMMAND_FAILED: 'WRAP_COMMAND_FAILED',
} as const
