# eslint-disable github-actions/on
name: request-org-eslint-update-plan

on:
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: request-org-eslint-update-plan
  cancel-in-progress: false

jobs:
  request:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - run: echo "Requesting organization ESLint update plan migration"
